version: '2'
services:
  server:
    build: ./WatServer
    ports:
     - "50051"
    volumes:
     - .:/go/src/github.com/EricLewe/TerminalChat/WatServer
    working_dir: /go/src/github.com/EricLewe/TerminalChat/WatServer
    command: go run WatServer/main.go
  client:
    build: ./WatClient
    network_mode: "service:server"
    depends_on:
     - server
    volumes:
     - .:/go/src/github.com/EricLewe/TerminalChat/WatClient
    working_dir: /go/src/github.com/EricLewe/TerminalChat/WatClient
    command: go run WatClient/main.go
  clientapi:
    build: ./WatClientApiLib
    depends_on:
     - client
    volumes:
     - .:/go/src/github.com/EricLewe/TerminalChat/WatClientApiLib
    working_dir: /go/src/github.com/EricLewe/TerminalChat/WatClientApiLib
